server:
  # 服务器端口
  port: 8333
spring:
  application:
    # 服务名
    name: service-gateway
  profiles:
    # 环境配置： dev test prod
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #设置路由id
        - id: service-vod
          #设置路由的uri
          uri: lb://service-vod
          #设置路由断言,代理service Id为auth-service的/auth/路径
          predicates:
            - Path=/*/vod/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**

